"""remove unique constraint from color.name

Revision ID: 0245e4ac189d
Revises: 56b816f2e924
Create Date: 2025-07-27 19:38:42.873560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0245e4ac189d'
down_revision: Union[str, Sequence[str], None] = '56b816f2e924'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('color_name_key'), 'color', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('color_name_key'), 'color', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
