"""add unit_price to profile

Revision ID: 0950ea57718f
Revises: bccf8eedbe13
Create Date: 2025-07-29 23:44:52.565383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0950ea57718f'
down_revision: Union[str, Sequence[str], None] = 'bccf8eedbe13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('unit_price', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'unit_price')
    # ### end Alembic commands ###
