"""create system_template tables

Revision ID: 16340b18a59a
Revises: 7aac17830ac0
Create Date: 2025-07-14 23:30:25.236519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '16340b18a59a'
down_revision: Union[str, Sequence[str], None] = '7aac17830ac0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('system_glass_template',
    # sa.Column('id', sa.UUID(), nullable=False),
    # sa.Column('system_variant_id', sa.UUID(), nullable=False),
    # sa.Column('glass_type_id', sa.UUID(), nullable=False),
    # sa.Column('formula_width', sa.String(), nullable=False),
    # sa.Column('formula_height', sa.String(), nullable=False),
    # sa.Column('formula_count', sa.String(), nullable=False),
    # sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    # sa.ForeignKeyConstraint(['glass_type_id'], ['glass_type.id'], ),
    # sa.ForeignKeyConstraint(['system_variant_id'], ['system_variant.id'], ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_table('system_material_template',
    # sa.Column('id', sa.UUID(), nullable=False),
    # sa.Column('system_variant_id', sa.UUID(), nullable=False),
    # sa.Column('material_id', sa.UUID(), nullable=False),
    # sa.Column('formula_quantity', sa.String(), nullable=False),
    # sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    # sa.ForeignKeyConstraint(['material_id'], ['other_material.id'], ),
    # sa.ForeignKeyConstraint(['system_variant_id'], ['system_variant.id'], ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_table('system_profile_template',
    # sa.Column('id', sa.UUID(), nullable=False),
    # sa.Column('system_variant_id', sa.UUID(), nullable=False),
    # sa.Column('profile_id', sa.UUID(), nullable=False),
    # sa.Column('formula_cut_length', sa.String(), nullable=False),
    # sa.Column('formula_cut_count', sa.String(), nullable=False),
    # sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    # sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    # sa.ForeignKeyConstraint(['system_variant_id'], ['system_variant.id'], ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('id')
    # )
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('project', 'customer_id',
    #            existing_type=sa.UUID(),
    #            nullable=True)
    # op.drop_table('system_profile_template')
    # op.drop_table('system_material_template')
    # op.drop_table('system_glass_template')
    pass
    # ### end Alembic commands ###
