"""Add color table and project profile/glass color

Revision ID: 2882257ab32a
Revises: ba6346f1bdb5
Create Date: 2025-07-26 17:40:18.317478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2882257ab32a'
down_revision: Union[str, Sequence[str], None] = 'ba6346f1bdb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('color',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('unit_cost', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('project', sa.Column('profile_color_id', sa.UUID(), nullable=True))
    op.add_column('project', sa.Column('glass_color_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'project', 'color', ['glass_color_id'], ['id'])
    op.create_foreign_key(None, 'project', 'color', ['profile_color_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.drop_column('project', 'glass_color_id')
    op.drop_column('project', 'profile_color_id')
    op.drop_table('color')
    # ### end Alembic commands ###
