"""add project_extra_profile and project_extra_glass

Revision ID: 355ef02a4eab
Revises: 4e676d4f472e
Create Date: 2025-07-26 23:26:46.153391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '355ef02a4eab'
down_revision: Union[str, Sequence[str], None] = '4e676d4f472e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_extra_glass',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('glass_type_id', sa.UUID(), nullable=False),
    sa.Column('width_mm', sa.Numeric(), nullable=False),
    sa.Column('height_mm', sa.Numeric(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('area_m2', sa.Numeric(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['glass_type_id'], ['glass_type.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_extra_profile',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('cut_length_mm', sa.Numeric(), nullable=False),
    sa.Column('cut_count', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_extra_profile')
    op.drop_table('project_extra_glass')
    # ### end Alembic commands ###
