"""add order_index to project system tables

Revision ID: 386423d21e5f
Revises: de6b88f9532f
Create Date: 2025-07-31 12:22:54.619193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '386423d21e5f'
down_revision: Union[str, Sequence[str], None] = 'de6b88f9532f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_system_glass', sa.Column('order_index', sa.Integer(), nullable=True))
    op.add_column('project_system_material', sa.Column('order_index', sa.Integer(), nullable=True))
    op.add_column('project_system_profile', sa.Column('order_index', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_system_profile', 'order_index')
    op.drop_column('project_system_material', 'order_index')
    op.drop_column('project_system_glass', 'order_index')
    # ### end Alembic commands ###
