"""add dealer profile fields to app_user

Revision ID: 4e0aee489f67
Revises: c41c62758024
Create Date: 2025-08-12 14:37:33.568975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e0aee489f67'
down_revision: Union[str, Sequence[str], None] = 'c41c62758024'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user', sa.Column('name', sa.String(length=100), nullable=True))
    op.add_column('app_user', sa.Column('email', sa.String(length=200), nullable=True))
    op.add_column('app_user', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('app_user', sa.Column('owner_name', sa.String(length=100), nullable=True))
    op.add_column('app_user', sa.Column('city', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'app_user', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'app_user', type_='unique')
    op.drop_column('app_user', 'city')
    op.drop_column('app_user', 'owner_name')
    op.drop_column('app_user', 'phone')
    op.drop_column('app_user', 'email')
    op.drop_column('app_user', 'name')
    # ### end Alembic commands ###
