"""add photo_url to system and system_variant

Revision ID: 56b816f2e924
Revises: a34967f46097
Create Date: 2025-07-27 01:23:39.404572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56b816f2e924'
down_revision: Union[str, Sequence[str], None] = 'a34967f46097'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system', sa.Column('photo_url', sa.String(length=300), nullable=True))
    op.add_column('system_variant', sa.Column('photo_url', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_variant', 'photo_url')
    op.drop_column('system', 'photo_url')
    # ### end Alembic commands ###
