"""Add created_at to project_system_profile, glass and material

Revision ID: 6b92d0f8668e
Revises: 6ff1f7a1fe8f
Create Date: 2025-07-31 00:47:51.647315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b92d0f8668e'
down_revision: Union[str, Sequence[str], None] = '6ff1f7a1fe8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_system_glass', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('project_system_material', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('project_system_profile', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_system_profile', 'created_at')
    op.drop_column('project_system_material', 'created_at')
    op.drop_column('project_system_glass', 'created_at')
    # ### end Alembic commands ###
