"""add unit_price to project_extra_profile

Revision ID: 6ff1f7a1fe8f
Revises: 0950ea57718f
Create Date: 2025-07-30 00:08:19.010035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ff1f7a1fe8f'
down_revision: Union[str, Sequence[str], None] = '0950ea57718f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_extra_profile', sa.Column('unit_price', sa.Numeric(), nullable=True))
    op.add_column('project_system_profile', sa.Column('unit_price', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_system_profile', 'unit_price')
    op.drop_column('project_extra_profile', 'unit_price')
    # ### end Alembic commands ###
