"""add formula_cut_length to system_material_template

Revision ID: a34967f46097
Revises: 355ef02a4eab
Create Date: 2025-07-26 23:51:38.198217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a34967f46097'
down_revision: Union[str, Sequence[str], None] = '355ef02a4eab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_material_template', sa.Column('formula_cut_length', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_material_template', 'formula_cut_length')
    # ### end Alembic commands ###
