"""add unit_price to profile (merge)

Revision ID: a3dd578426be
Revises: b69d0fc50fd9
Create Date: 2025-07-31 23:48:46.670466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3dd578426be'
down_revision: Union[str, Sequence[str], None] = 'b69d0fc50fd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('unit_price', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'unit_price')
    # ### end Alembic commands ###
