"""Remove color from project_system

Revision ID: ba6346f1bdb5
Revises: bbcae448a88b
Create Date: 2025-07-26 17:12:56.793932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba6346f1bdb5'
down_revision: Union[str, Sequence[str], None] = 'bbcae448a88b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_system', 'color')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_system', sa.Column('color', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
