"""Add project_kodu to project

Revision ID: bc5d48c0e649
Revises: 300af03e6d4d
Create Date: 2025-07-17 02:58:15.877042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc5d48c0e649'
down_revision: Union[str, Sequence[str], None] = '300af03e6d4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_extra_material',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('cut_length_mm', sa.Numeric(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['other_material.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('project',
        sa.Column('project_kodu', sa.String(length=50), nullable=False, server_default='TALU-10000')
    )
    op.create_unique_constraint('uq_project_project_kodu', 'project', ['project_kodu'])
        # 1) Varolan NULL customer_id’leri doldur
    op.execute("""
        UPDATE project
        SET customer_id = 'cccccccc-cccc-cccc-cccc-cccccccccccc'
        WHERE customer_id IS NULL
    """)
    # 2) Oluşturduğunuz sütunu NOT NULL yap
    op.alter_column(
        'project',
        'customer_id',
        existing_type=sa.UUID(),
        nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project', type_='unique')
    op.alter_column('project', 'customer_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('project', 'project_kodu')
    op.drop_table('project_extra_material')
    # ### end Alembic commands ###
