"""initial schema

Revision ID: c41c62758024
Revises: 
Create Date: 2025-08-01 14:41:32.707246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c41c62758024'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('color',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('unit_cost', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('glass_type',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cam_isim', sa.String(length=100), nullable=False),
    sa.Column('thickness_mm', sa.Numeric(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('other_material',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('diger_malzeme_isim', sa.String(length=100), nullable=False),
    sa.Column('birim', sa.String(length=20), nullable=False),
    sa.Column('birim_agirlik', sa.Numeric(), nullable=False),
    sa.Column('hesaplama_turu', sa.String(length=20), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profil_kodu', sa.String(length=50), nullable=False),
    sa.Column('profil_isim', sa.String(length=100), nullable=False),
    sa.Column('profil_kesit_fotograf', sa.TEXT(), nullable=True),
    sa.Column('birim_agirlik', sa.Numeric(), nullable=False),
    sa.Column('boy_uzunluk', sa.Numeric(), nullable=False),
    sa.Column('unit_price', sa.Numeric(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profil_kodu')
    )
    op.create_table('system',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('photo_url', sa.String(length=300), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('customer',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dealer_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['dealer_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_variant',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('system_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('photo_url', sa.String(length=300), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['system_id'], ['system.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_kodu', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('project_name', sa.String(length=100), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('profile_color_id', sa.UUID(), nullable=True),
    sa.Column('glass_color_id', sa.UUID(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['glass_color_id'], ['color.id'], ),
    sa.ForeignKeyConstraint(['profile_color_id'], ['color.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_kodu')
    )
    op.create_table('system_glass_template',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('system_variant_id', sa.UUID(), nullable=False),
    sa.Column('glass_type_id', sa.UUID(), nullable=False),
    sa.Column('formula_width', sa.String(), nullable=False),
    sa.Column('formula_height', sa.String(), nullable=False),
    sa.Column('formula_count', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['glass_type_id'], ['glass_type.id'], ),
    sa.ForeignKeyConstraint(['system_variant_id'], ['system_variant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_material_template',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('system_variant_id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('formula_quantity', sa.String(), nullable=False),
    sa.Column('formula_cut_length', sa.String(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['other_material.id'], ),
    sa.ForeignKeyConstraint(['system_variant_id'], ['system_variant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_profile_template',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('system_variant_id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('formula_cut_length', sa.String(), nullable=False),
    sa.Column('formula_cut_count', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.ForeignKeyConstraint(['system_variant_id'], ['system_variant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_extra_glass',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('glass_type_id', sa.UUID(), nullable=False),
    sa.Column('width_mm', sa.Numeric(), nullable=False),
    sa.Column('height_mm', sa.Numeric(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('area_m2', sa.Numeric(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['glass_type_id'], ['glass_type.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_extra_material',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('cut_length_mm', sa.Numeric(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['other_material.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_extra_profile',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('cut_length_mm', sa.Numeric(), nullable=False),
    sa.Column('cut_count', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_system',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('system_variant_id', sa.UUID(), nullable=False),
    sa.Column('width_mm', sa.Numeric(), nullable=False),
    sa.Column('height_mm', sa.Numeric(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['system_variant_id'], ['system_variant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_order',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_no', sa.String(length=50), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('order_name', sa.String(length=100), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_no')
    )
    op.create_table('order_item',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('project_system_id', sa.UUID(), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('width_mm', sa.Numeric(), nullable=False),
    sa.Column('height_mm', sa.Numeric(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['sales_order.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_system_id'], ['project_system.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_system_glass',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_system_id', sa.UUID(), nullable=False),
    sa.Column('glass_type_id', sa.UUID(), nullable=False),
    sa.Column('width_mm', sa.Numeric(), nullable=False),
    sa.Column('height_mm', sa.Numeric(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('area_m2', sa.Numeric(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['glass_type_id'], ['glass_type.id'], ),
    sa.ForeignKeyConstraint(['project_system_id'], ['project_system.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_system_material',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_system_id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('cut_length_mm', sa.Numeric(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['other_material.id'], ),
    sa.ForeignKeyConstraint(['project_system_id'], ['project_system.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_system_profile',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_system_id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('cut_length_mm', sa.Numeric(), nullable=False),
    sa.Column('cut_count', sa.Integer(), nullable=False),
    sa.Column('total_weight_kg', sa.Numeric(), nullable=True),
    sa.Column('unit_price', sa.Numeric(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.ForeignKeyConstraint(['project_system_id'], ['project_system.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_item_extra_material',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_item_id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('cut_length_mm', sa.Numeric(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['other_material.id'], ),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_item_glass',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_item_id', sa.UUID(), nullable=False),
    sa.Column('glass_type_id', sa.UUID(), nullable=False),
    sa.Column('width_mm', sa.Numeric(), nullable=False),
    sa.Column('height_mm', sa.Numeric(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('area_m2', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['glass_type_id'], ['glass_type.id'], ),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_item_material',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_item_id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('cut_length_mm', sa.Numeric(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['other_material.id'], ),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_item_profile',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_item_id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('cut_length_mm', sa.Numeric(), nullable=False),
    sa.Column('cut_count', sa.Integer(), nullable=False),
    sa.Column('total_weight_kg', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_item_profile')
    op.drop_table('order_item_material')
    op.drop_table('order_item_glass')
    op.drop_table('order_item_extra_material')
    op.drop_table('project_system_profile')
    op.drop_table('project_system_material')
    op.drop_table('project_system_glass')
    op.drop_table('order_item')
    op.drop_table('sales_order')
    op.drop_table('project_system')
    op.drop_table('project_extra_profile')
    op.drop_table('project_extra_material')
    op.drop_table('project_extra_glass')
    op.drop_table('system_profile_template')
    op.drop_table('system_material_template')
    op.drop_table('system_glass_template')
    op.drop_table('project')
    op.drop_table('system_variant')
    op.drop_table('customer')
    op.drop_table('system')
    op.drop_table('profile')
    op.drop_table('other_material')
    op.drop_table('glass_type')
    op.drop_table('color')
    op.drop_table('app_user')
    # ### end Alembic commands ###
