"""add project_system_* tables

Revision ID: d85511332d86
Revises: 0f8bccdb35dc
Create Date: 2025-07-13 19:34:45.752666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd85511332d86'
down_revision: Union[str, Sequence[str], None] = '78b232872b85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.create_table('project_system_glass',
    #sa.Column('id', sa.UUID(), nullable=False),
    #sa.Column('project_system_id', sa.UUID(), nullable=False),
    #sa.Column('glass_type_id', sa.UUID(), nullable=False),
    #sa.Column('width_mm', sa.Numeric(), nullable=False),
    #sa.Column('height_mm', sa.Numeric(), nullable=False),
    #sa.Column('count', sa.Integer(), nullable=False),
    #sa.Column('area_m2', sa.Numeric(), nullable=True),
    #sa.ForeignKeyConstraint(['glass_type_id'], ['glass_type.id'], ),
    #sa.ForeignKeyConstraint(['project_system_id'], ['project_system.id'], ondelete='CASCADE'),
    #sa.PrimaryKeyConstraint('id')
    #)
    #op.create_table('project_system_material',
    #sa.Column('id', sa.UUID(), nullable=False),
    #sa.Column('project_system_id', sa.UUID(), nullable=False),
    #sa.Column('material_id', sa.UUID(), nullable=False),
    #sa.Column('cut_length_mm', sa.Numeric(), nullable=True),
    #sa.Column('count', sa.Integer(), nullable=False),
    #sa.ForeignKeyConstraint(['material_id'], ['other_material.id'], ),
    #sa.ForeignKeyConstraint(['project_system_id'], ['project_system.id'], ondelete='CASCADE'),
    #sa.PrimaryKeyConstraint('id')
    #)
    #op.create_table('project_system_profile',
    #sa.Column('id', sa.UUID(), nullable=False),
    #sa.Column('project_system_id', sa.UUID(), nullable=False),
    #sa.Column('profile_id', sa.UUID(), nullable=False),
    #sa.Column('cut_length_mm', sa.Numeric(), nullable=False),
    #sa.Column('cut_count', sa.Integer(), nullable=False),
    #sa.Column('total_weight_kg', sa.Numeric(), nullable=True),
    #sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    #sa.ForeignKeyConstraint(['project_system_id'], ['project_system.id'], ondelete='CASCADE'),
    #sa.PrimaryKeyConstraint('id')
    #)
    #op.add_column('project', sa.Column('customer_id', sa.UUID(), nullable=True))
    op.execute(
        "UPDATE project "
        "SET created_by = 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa' "
        "WHERE created_by IS NULL"
    )
    op.alter_column('project', 'created_by',
            existing_type=sa.UUID(),
            nullable=False)
    #op.add_column('project', sa.Column('order_no', sa.String(length=50), nullable=True))
    #op.add_column('project', sa.Column('order_date', sa.Date(), nullable=True))
    #op.add_column('project', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    #op.add_column('project', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('project', 'created_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('project_created_by_fkey'), 'project', type_='foreignkey')
    op.create_foreign_key(None, 'project', 'app_user', ['created_by'], ['id'])
    op.create_foreign_key(None, 'project', 'customer', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.create_foreign_key(op.f('project_created_by_fkey'), 'project', 'app_user', ['created_by'], ['id'], ondelete='SET NULL')
    op.alter_column('project', 'created_by',
               existing_type=sa.UUID(),
               nullable=True)
    #op.drop_column('project', 'updated_at')
    #op.drop_column('project', 'created_at')
    #op.drop_column('project', 'order_date')
    #op.drop_column('project', 'order_no')
    #op.drop_column('project', 'customer_id')
    #op.drop_table('project_system_profile')
    #op.drop_table('project_system_material')
    #op.drop_table('project_system_glass')
    # ### end Alembic commands ###
