"""add order_index to system templates

Revision ID: de6b88f9532f
Revises: 6ff1f7a1fe8f
Create Date: 2025-07-31 11:29:08.369063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de6b88f9532f'
down_revision: Union[str, Sequence[str], None] = '6ff1f7a1fe8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_glass_template', sa.Column('order_index', sa.Integer(), nullable=True))
    op.add_column('system_material_template', sa.Column('order_index', sa.Integer(), nullable=True))
    op.add_column('system_profile_template', sa.Column('order_index', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_profile_template', 'order_index')
    op.drop_column('system_material_template', 'order_index')
    op.drop_column('system_glass_template', 'order_index')
    # ### end Alembic commands ###
