"""soft delete flags for catalog + publish flags for system & variant

Revision ID: fb27cc598548
Revises: 94b793dfa665
Create Date: 2025-08-21 22:51:49.633616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb27cc598548'
down_revision: Union[str, Sequence[str], None] = '94b793dfa665'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('color', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('color', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('glass_type', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('glass_type', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('other_material', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('other_material', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('profile', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('profile', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_unique_constraint(None, 'project', ['project_kodu'])
    op.add_column('system', sa.Column('is_published', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('system', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('system_variant', sa.Column('is_published', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('system_variant', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_variant', 'is_deleted')
    op.drop_column('system_variant', 'is_published')
    op.drop_column('system', 'is_deleted')
    op.drop_column('system', 'is_published')
    op.drop_constraint(None, 'project', type_='unique')
    op.drop_column('profile', 'is_deleted')
    op.drop_column('profile', 'is_active')
    op.drop_column('other_material', 'is_deleted')
    op.drop_column('other_material', 'is_active')
    op.drop_column('glass_type', 'is_deleted')
    op.drop_column('glass_type', 'is_active')
    op.drop_column('color', 'is_deleted')
    op.drop_column('color', 'is_active')
    # ### end Alembic commands ###
